### ISSUE TITLE
Strange way to finding cameras

### ISSUE THREAD

**Issue by ArtemyMagarin** [yaiestura/flask_api#2]
Using the [WSDiscovery](https://pypi.org/project/WSDiscovery/) library may be the best solution for this project.

**Comment by ArtemyMagarin** [comment]
done

**Comment by yaiestura** [comment]
Fixed ONVIF Discovery by using [WSDIscovery Python library](https://pypi.org/project/WSDiscovery/), but still script discoveres devices on 10.0.3 network. Solution may be to ignore this network in discovery process.
